version: '3.8'

services:
  app:
    build: .
    working_dir: /src
    ports:
      - "8000:8000"
    volumes:
      - .:/src
    environment:
      ENV: production
    command: poetry run streamlit run src/app/main.py --server.port 8502

